---
apiVersion: v1
kind: Namespace
metadata:
  name: busybox-odr-cephfs-sample
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: busybox-odr-cephfs-channel
  namespace: busybox-odr-cephfs-sample
spec:
  pathname: https://github.com/red-hat-storage/ocm-ramen-samples
  type: Git
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: release-4.12
    apps.open-cluster-management.io/git-path: busybox-odr-cephfs
  labels:
    app: busybox-odr-cephfs
  name: busybox-odr-cephfs-subscription
  namespace: busybox-odr-cephfs-sample
spec:
  channel: busybox-odr-cephfs-sample/busybox-odr-cephfs-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: busybox-odr-cephfs-placement
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: busybox-odr-cephfs
  namespace: busybox-odr-cephfs-sample
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - busybox-odr-cephfs
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: busybox-odr-cephfs
  name: busybox-odr-cephfs-placement
  namespace: busybox-odr-cephfs-sample
spec:
  clusterSelector:
    matchLabels:
      name: dr02
